@startuml

skinparam backgroundColor #FFF
skinparam handwritten true

note as N1
 Disruptor 实现的生产消费模式
end note

class PCData{
    - initData : int
    + getData(): int
}

RingBuffer .down.> PCData

Consumer o-right-> RingBuffer
Consumer .down.> PCData
Producer o-left-> RingBuffer
Producer ..> PCData

Main ..> Consumer
Main ..> Producer
Main ..> RingBuffer

@enduml